### ISSUE TITLE
Might want to remove Tumblr specific entries from default configs

### ISSUE THREAD

**Issue by jsjohnst** [tumblr/genesis#20]
If you take a look here: https://github.com/tumblr/genesis/blob/master/testenv/bootbox/web/config/config.yml

There's a bunch of URLs and filenames which are Tumblr specific. 

As the Virident setup tasks aren't included in the public repo, not sure why the config entries for them were even left in.

Also, while not inherently "bad" per say, probably not wise exposing nexus / AAA / Collins / mrepo internal Tumblr host names and file system structures either.

**Comment by maddalab** [comment]
https://github.com/tumblr/genesis/pull/24

**Comment by maddalab** [comment]
Resolving, obviously pending merging of PR
